 create table pastDuePayments(
    idPastDuePayment varchar(40),
	idCategory varchar(40),
    nameCategory varchar(40),
    typeCategory char(3),
    idParentCategory varchar(40),
    nameParentCategory varchar(50),
    idCostCenter varchar(40),
    percentCostCenter decimal(12, 2),
    descriptionCostCenter varchar(50),
    costCenterIsDeleted boolean,
    idSchedule varchar(40),
    type char(10),
    isEntry boolean,
    isBill boolean,
    isDebitNote boolean,
    isFlagged boolean,
    isDued boolean,
    dueDate datetime,
    accrualDate datetime,
    scheduleDate datetime,
    createDate datetime,
    value decimal(12, 2),
    isPaid boolean,
    costCenterValueType int,
    paidValue decimal(12, 2),
    openValue decimal(12, 2),
    idStakeholder varchar(40),
    nameStakeholder varchar(240),
    typeStakeholder varchar(40),
    stakeholderIsDeleted boolean,
    description varchar(250),
    reference varchar(50),
    hasInstallment boolean,
    idInstallment varchar(40),
    hasRecurrence boolean,
    hasOpenEntryPromise boolean,
    hasEntryPromise boolean,
    autoGenerateEntryPromise boolean,
    hasInvoice boolean,
    hasPendingInvoice boolean,
    hasScheduleInvoice boolean,
    autoGenerateNfseType int,
    isPaymentScheduled boolean
);