create table internalIncomingBills(
	entryId varchar(40),
    bankBalanceDateIsGreaterThanEntryDate boolean,
    isVirtual boolean,
    accountId varchar(40),
    accountName varchar(100),
    accountIsDeleted boolean,
    date datetime,
    identifier varchar(100),
    value decimal(12, 2),
    checkNumber varchar(200),
    isReconciliated boolean,
    isTransfer boolean,
    isFlagged boolean
);

create table externalIncomingBills(
	entryId varchar(40),
    bankBalanceDateIsGreaterThanEntryDate boolean,
    scheduleId varchar(40),
    isVirtual boolean,
    accountId varchar(40),
    accountName varchar(150),
    accountIsDeleted boolean,
    stakeholderId varchar(40),
    stakeholderName varchar(150),
    stakeholderIsDeleted boolean,
    categoryId varchar(40),
    categoryName varchar(50),
    categoryIsDeleted boolean,
    categoryType char(3),
    categoryParentId varchar(40),
    categoryParentName varchar(50),
    date datetime,
    identifier varchar(50),
    value decimal (12, 2),
    description varchar(150),
    checkNumber varchar(200),
    isReconciliated boolean,
    isTransfer boolean,
    isFlagged boolean,
    costCenterId varchar(40), 
    costCenterName varchar(50),
    costCenterPercent decimal(12, 2),
    costCenterValue decimal(12, 2),
    negativo boolean
);