CREATE TABLE scheduledPayments (
    scheduleId VARCHAR(40),
    categoryId VARCHAR(40),
    categoryName VARCHAR(100),
    categoryType CHAR(3),
    categoryParentId VARCHAR(40),
    categoryParentName VARCHAR(50),
    costCenterId VARCHAR(40),
    costCenterName VARCHAR(50),
    costCenterPercent DECIMAL(12 , 2 ),
    type CHAR(10),
    isEntry BOOLEAN,
    isBill BOOLEAN,
    isDebitNote BOOLEAN,
    isFlagged BOOLEAN,
    isDued BOOLEAN,
    dueDate DATETIME,
    accrualDate DATETIME,
    scheduleDate DATETIME,
    deleteDate DATETIME,
    createDate DATETIME,
    value DECIMAL(12 , 2 ),
    isPaid BOOLEAN,
    costCenterValueType INT,
    paidValue DECIMAL(12 , 2 ),
    openValue DECIMAL(12 , 2 ),
    stakeholderType VARCHAR(20),
    stakeholderId VARCHAR(40),
    stakeholderName VARCHAR(250),
    stakeholderIsDeleted BOOLEAN,
    description VARCHAR(250),
    hasInstallment BOOLEAN,
    installmentId varchar(40),
    hasRecurrence BOOLEAN,
    hasOpenEntryPromise BOOLEAN,
    hasEntryPromise BOOLEAN,
    autoGenerateEntryPromise BOOLEAN,
    hasInvoice BOOLEAN,
    hasPendingInvoice BOOLEAN,
    hasScheduleInvoice BOOLEAN,
    autoGenerateNfseType INT,
    isPaymentScheduled BOOLEAN
);