 create table past_due_payments(
	category_id varchar(40),
    category_name varchar(40),
    category_type char(3),
    category_parent_id varchar(40),
    category_parent_name varchar(50),
    cost_center_id varchar(40),
    cost_center_percent decimal(12, 2),
    cost_center_description varchar(50),
    cost_center_is_deleted boolean,
    schedule_id varchar(40),
    type char(10),
    is_entry boolean,
    is_bill boolean,
    is_debit_note boolean,
    is_flagged boolean,
    is_dued boolean,
    due_date datetime,
    accrual_date datetime,
    schedule_date datetime,
    create_date datetime,
    value decimal(12, 2),
    is_paid boolean,
    cost_center_value_type int,
    paid_value decimal(12, 2),
    open_value decimal(12, 2),
    stakeholder_id varchar(40),
    stakeholder_name varchar(40),
    stakeholder_type varchar(40),
    stakeholder_is_deleted boolean,
    description varchar(50),
    reference varchar(50),
    has_installment boolean,
    installment_id varchar(40),
    has_recurrence boolean,
    has_open_entry_promise boolean,
    has_entry_promise boolean,
    auto_generate_entry_promise boolean,
    has_invoice boolean,
    has_pending_invoice boolean,
    has_schedule_invoice boolean,
    auto_generate_nfse_type int,
    is_payment_scheduled boolean
);




select * from past_due_payments