create table payments_receivable(
     id varchar(40),
     category_id varchar(40),
     category_name varchar(50),
     value decimal(12, 2),
     type char(3),
     parent varchar(50),
     parent_id varchar(40),
     schedule_id varchar(40),
     type_operation char(10),
     is_entry boolean,
	 is_bill boolean,
     is_debite_node boolean,
     is_flagged boolean,
     is_dued boolean,
     due_date datetime,
     accrual_date datetime,
     schedule_date datetime,
     create_date datetime,
     is_paid boolean,
     cost_center_value_type int,
     paid_value decimal(12,2),
     open_value decimal(12,2),
     stakeholder_id varchar(40),
     stakeholder_type char(15),
     stakeholder_name varchar(50),
     stakeholder_is_deleted boolean,
     description varchar(50),
     reference varchar(40),
     has_installment boolean,
     installment_id varchar(40),
     has_recurrence boolean,
     has_open_entry_promise boolean,
     has_entry_promise boolean,
     auto_generate_entry_promise boolean,
     has_invoice boolean,
     has_pending_invoice boolean,
     has_schedule_invoice boolean,
     auto_generate_nfse_type int,
     is_payment_scheduled boolean,
     foreign key (category_id) references child_category_aux(child_id),
     foreign key (stakeholder_id) references stakeholder(id)
 )	
 
